var SystemDispatcher = require('../dispatcher/system-dispatcher');
var SystemConstants = require('../constants/system-constants');

var ActionTypes = SystemConstants.ActionTypes;

module.exports = {
	receivedErrorMsg:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_ERROR_MSG,
            data:data
        })
    },
    receivedUserInfo:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_USER_INFO,
            data:data
        })
    },
    receivedStudentInfo:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_STUDENT_INFO,
            data:data
        })
    },
    postedUserLoginForm:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.POSTED_USER_LOGIN_FORM,
            data:data
        })
    },
	postedUserLogoutForm:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.POSTED_USER_LOGOUT_FORM,
            data:data
        })
	},
	postedUserNewPassword:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.POSTED_USER_NEW_PASSWORD,
            data:data
        })
	},
	postedUserFeedback:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.POSTED_USER_FEEDBACK,
            data:data
        })
	},
	receivedProvinces:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_PROVINCES,
            data:data
        })
	},
    changedAddressForm:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.CHANGED_ADDRESS_FORM,
            data:data
        })
    },
	receivedCategory:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_CATEGORY,
            data:data
        })
	},
	changedCategoryForm:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.CHANGED_CATEGORY_FORM,
            data:data
        })
	},
	changedDatePickerForm:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.CHANGED_DATE_PICKER_FORM,
            data:data
        })
	},
    receivedAllData:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_ALL_DATA,
            data:data
        })
    },
    receivedStudentMeta:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_STUDENT_META,
            data:data
        })
    },
    receivedExamErrorTopicNum:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_EXAM_ERROR_TOPIC_NUM,
            data:data
        })
    },
    receivedExamErrorTopic:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_EXAM_ERROR_TOPIC,
            data:data
        })
    },
    receivedTopicSuggest:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_TOPIC_SUGGEST,
            data:data
        })
    },
    receivedSubjectAttrs:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_SUBATTRS,
            data:data
        })
    },
    receivedAllExamInfo:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_ALL_EXAM_INFO,
            data:data
        })
    },
    receivedKnowMap:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_KONW_MAP,
            data:data
        })
    },
    receivedStudentInfo:function(data){
        SystemDispatcher.dispatch({
            type:ActionTypes.RECEIVED_STUDENT_INFO,
            data:data
        })
    }
}